language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: pejPtcP1pdV+h1QHZ8zheWgLzohwn3zGy6FsHIrukVBS/r6lqaOeVBuhcGLItnZpf/skp9QhHvPdt1tdxWr4rpi/A3l/+ELIKw14cr4y86IhMPh7a6FDB9Y+j6R5NfNZe7zS5nKA9vTV8xTRzL+8R/0n89b9ZJx1i26JZuzv58XGnU4x/iGorvtEQIQ77REKPVab1lRe8qihERJzlUd7BA5RSQzs8xFHGSe3I4Oy7HLlCyeJsciFu9QrpT/TsmbFugGcBven9rR7wrBwm8bcHeLWHBv6u+MEeMBC3w08i0Cs8Maewk8WQVT31wQVgwoE+y5gIyyu7xQqp1TRbf1W0jQ3i2LhQepWCaWuLBknasqxkhLhNY/K05otdA1hzSFByDbq5wx1/vNmn03A2fZ9PW/WBXb+fUjxDJInR283N6gWevPgGJ9ZrZFvmdqROi9fCYiLVk3H8cw3qa59NUAH+U9GxFdN1d6MyRvNnTd0pAUrbk5a/LiaMe0o6Wa/6pyhffexjUQL04VLQjwM6Cv5+DfYS+Ku8LjOmFedW4QpiUF5q2wVJ/qTKq+QtT3xT9E98sQade9mltSPy3M+YVOzirR9wTtr7HFgll6zZBDaQKplT58hBjYeoiFhU9jGGq8eO4d/NMyWkDo5Yad43zQukeu2Fo6/Qo0J50w77CEHEXw=
  file:
    - "hast-util-sectioning.js"
    - "hast-util-sectioning.min.js"
  on:
    tags: true
